// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'stream_listener_mixin_test.dart' as stream_listener_mixin_test;

void main() {
  stream_listener_mixin_test.main();
}
