name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stream_listener:
    path: ../

dev_dependencies:
  very_good_analysis: ^2.1.1
