name: stream_listener
description: Dart package that helps manage streams and subscriptions. Built in order to reduce the complexity of having to manually subscribe to streams and cancel subscriptions.
version: 3.0.0
homepage: https://github.com/felangel/stream_listener

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.5
  very_good_analysis: ^2.1.1
